"""add_waiting_for_dice_column

Revision ID: b749491a47a8
Revises: ee849f9d15e3
Create Date: 2025-05-26 12:19:14.961995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b749491a47a8'
down_revision: Union[str, None] = 'ee849f9d15e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('world_states', sa.Column('pending_dice_requirement', sa.JSON(), nullable=True))
    op.add_column('world_states', sa.Column('last_dice_result', sa.JSON(), nullable=True))
    op.add_column('world_states', sa.Column('waiting_for_dice', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('world_states', 'waiting_for_dice')
    op.drop_column('world_states', 'last_dice_result')
    op.drop_column('world_states', 'pending_dice_requirement')
    # ### end Alembic commands ###
