"""Initial database schema

Revision ID: cf61c0077e8c
Revises: 
Create Date: 2025-05-23 10:02:43.718171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf61c0077e8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('race', sa.String(length=50), nullable=False),
    sa.Column('character_class', sa.String(length=50), nullable=False),
    sa.Column('background', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('constitution', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('wisdom', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience_points', sa.Integer(), nullable=False),
    sa.Column('max_hit_points', sa.Integer(), nullable=False),
    sa.Column('current_hit_points', sa.Integer(), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('proficiencies', sa.JSON(), nullable=False),
    sa.Column('skill_proficiencies', sa.JSON(), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=False),
    sa.Column('equipped_items', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('backstory', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_index(op.f('ix_characters_user_id'), 'characters', ['user_id'], unique=False)
    op.create_table('enemy_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('creature_type', sa.Enum('ABERRATION', 'BEAST', 'CELESTIAL', 'CONSTRUCT', 'DRAGON', 'ELEMENTAL', 'FEY', 'FIEND', 'GIANT', 'HUMANOID', 'MONSTROSITY', 'OOZE', 'PLANT', 'UNDEAD', name='creaturetype'), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('challenge_rating', sa.Float(), nullable=False),
    sa.Column('alignment', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('constitution', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('wisdom', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.Column('hit_points', sa.Integer(), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('speed', sa.String(length=50), nullable=False),
    sa.Column('proficiency_bonus', sa.Integer(), nullable=False),
    sa.Column('saving_throws', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('damage_resistances', sa.JSON(), nullable=True),
    sa.Column('damage_immunities', sa.JSON(), nullable=True),
    sa.Column('condition_immunities', sa.JSON(), nullable=True),
    sa.Column('senses', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('attacks', sa.JSON(), nullable=True),
    sa.Column('special_abilities', sa.JSON(), nullable=True),
    sa.Column('loot_table', sa.JSON(), nullable=True),
    sa.Column('xp_value', sa.Integer(), nullable=False),
    sa.Column('tactics', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enemy_templates_id'), 'enemy_templates', ['id'], unique=False)
    op.create_index(op.f('ix_enemy_templates_name'), 'enemy_templates', ['name'], unique=False)
    op.create_table('story_arcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('story_type', sa.String(length=20), nullable=True),
    sa.Column('current_stage', sa.Enum('INTRO', 'INCITING_INCIDENT', 'FIRST_COMBAT', 'TWIST', 'FINAL_CONFLICT', 'RESOLUTION', name='storystage'), nullable=False),
    sa.Column('stages_completed', sa.JSON(), nullable=True),
    sa.Column('major_decisions', sa.JSON(), nullable=True),
    sa.Column('npc_status', sa.JSON(), nullable=True),
    sa.Column('combat_outcomes', sa.JSON(), nullable=True),
    sa.Column('story_completed', sa.Boolean(), nullable=True),
    sa.Column('completion_type', sa.String(length=50), nullable=True),
    sa.Column('final_rewards', sa.JSON(), nullable=True),
    sa.Column('story_seed', sa.Text(), nullable=True),
    sa.Column('ai_context_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_arcs_character_id'), 'story_arcs', ['character_id'], unique=False)
    op.create_index(op.f('ix_story_arcs_id'), 'story_arcs', ['id'], unique=False)
    op.create_table('combat_encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_arc_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('encounter_name', sa.String(length=200), nullable=True),
    sa.Column('encounter_type', sa.String(length=50), nullable=False),
    sa.Column('combat_state', sa.Enum('NOT_STARTED', 'INITIATIVE', 'IN_PROGRESS', 'VICTORY', 'DEFEAT', 'RETREAT', name='combatstate'), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('current_turn', sa.Integer(), nullable=True),
    sa.Column('initiative_order', sa.JSON(), nullable=True),
    sa.Column('victory_conditions', sa.JSON(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('xp_awarded', sa.Integer(), nullable=True),
    sa.Column('loot_awarded', sa.JSON(), nullable=True),
    sa.Column('combat_log', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['story_arc_id'], ['story_arcs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combat_encounters_character_id'), 'combat_encounters', ['character_id'], unique=False)
    op.create_index(op.f('ix_combat_encounters_id'), 'combat_encounters', ['id'], unique=False)
    op.create_index(op.f('ix_combat_encounters_story_arc_id'), 'combat_encounters', ['story_arc_id'], unique=False)
    op.create_table('world_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_arc_id', sa.Integer(), nullable=False),
    sa.Column('current_location', sa.String(length=100), nullable=False),
    sa.Column('explored_areas', sa.JSON(), nullable=True),
    sa.Column('world_events', sa.JSON(), nullable=True),
    sa.Column('active_objectives', sa.JSON(), nullable=True),
    sa.Column('completed_objectives', sa.JSON(), nullable=True),
    sa.Column('world_items', sa.JSON(), nullable=True),
    sa.Column('story_time_elapsed', sa.Integer(), nullable=True),
    sa.Column('real_time_played', sa.Integer(), nullable=True),
    sa.Column('established_lore', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['story_arc_id'], ['story_arcs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_states_id'), 'world_states', ['id'], unique=False)
    op.create_index(op.f('ix_world_states_story_arc_id'), 'world_states', ['story_arc_id'], unique=False)
    op.create_table('combat_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('combat_encounter_id', sa.Integer(), nullable=False),
    sa.Column('participant_type', sa.String(length=20), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('enemy_template_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_hit_points', sa.Integer(), nullable=False),
    sa.Column('current_hit_points', sa.Integer(), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('initiative', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('active_conditions', sa.JSON(), nullable=True),
    sa.Column('temporary_hp', sa.Integer(), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('movement_remaining', sa.Integer(), nullable=True),
    sa.Column('actions_taken', sa.JSON(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('eliminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['combat_encounter_id'], ['combat_encounters.id'], ),
    sa.ForeignKeyConstraint(['enemy_template_id'], ['enemy_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combat_participants_combat_encounter_id'), 'combat_participants', ['combat_encounter_id'], unique=False)
    op.create_index(op.f('ix_combat_participants_id'), 'combat_participants', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_combat_participants_id'), table_name='combat_participants')
    op.drop_index(op.f('ix_combat_participants_combat_encounter_id'), table_name='combat_participants')
    op.drop_table('combat_participants')
    op.drop_index(op.f('ix_world_states_story_arc_id'), table_name='world_states')
    op.drop_index(op.f('ix_world_states_id'), table_name='world_states')
    op.drop_table('world_states')
    op.drop_index(op.f('ix_combat_encounters_story_arc_id'), table_name='combat_encounters')
    op.drop_index(op.f('ix_combat_encounters_id'), table_name='combat_encounters')
    op.drop_index(op.f('ix_combat_encounters_character_id'), table_name='combat_encounters')
    op.drop_table('combat_encounters')
    op.drop_index(op.f('ix_story_arcs_id'), table_name='story_arcs')
    op.drop_index(op.f('ix_story_arcs_character_id'), table_name='story_arcs')
    op.drop_table('story_arcs')
    op.drop_index(op.f('ix_enemy_templates_name'), table_name='enemy_templates')
    op.drop_index(op.f('ix_enemy_templates_id'), table_name='enemy_templates')
    op.drop_table('enemy_templates')
    op.drop_index(op.f('ix_characters_user_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
